ISSUE-62: provide an interface to get in-sync followers
eBay/Gringofts pull request #63
Opened 2022-01-26 07:06 UTC by crystal-xu

2022-02-03 03:01 UTC, jackyjia commented
- [ ] every commit must be signed
- [ ] prefix each commit message with issue number
- [ ] link this PR to the issue

2022-03-23 10:58 UTC, crystal-xu commented
> * [ ]  every commit must be signed
> * [ ]  prefix each commit message with issue number
> * [ ]  link this PR to the issue
> * [ ]  give this PR an owner
> * [ ]  mark this PR with proper labels (e.g., wip, ready for review)

Hi jj, it seems that I don't have the permission to assign assignees or request reviewers, would you please help?

2022-03-24 08:10 UTC, huyumars requested changes

2022-03-24 08:10 UTC, huyumars commented on src/infra/raft/v2/RaftCore.cpp
> +            [](MemberOffsetInfo x, MemberOffsetInfo y) { return x.mId > y.mId; });
const &

2022-03-24 08:10 UTC, huyumars commented on src/infra/raft/RaftInterface.h
> +  virtual void getInSyncFollowers(const int64_t &, std::vector<MemberOffsetInfo> *) const = 0;
return leader offset and followers' offset

2022-03-24 08:11 UTC, huyumars requested changes

2022-03-24 08:11 UTC, huyumars commented on src/infra/raft/v2/RaftCore.cpp
> +            [](MemberOffsetInfo x, MemberOffsetInfo y) { return x.mId > y.mId; });
Don't sort at infra level

2022-03-25 01:57 UTC, huyumars commented on src/infra/raft/v2/RaftCore.cpp
> +  mMemberOffsets->push_back({mSelfInfo.mId, mSelfInfo.mAddress, mMajorityIndex, true});
emplace_back

2022-03-25 01:57 UTC, huyumars commented on src/infra/raft/v2/RaftCore.cpp
> +    mMemberOffsets->push_back(peerOffset);
emplace_back

2022-03-25 01:57 UTC, huyumars commented on src/infra/raft/v2/RaftCore.h
> +  std::atomic<uint64_t> mMajorityIndex = 0;
just use commited index

2022-03-25 03:39 UTC, crystal-xu commented
Using commit index instead of majority index as leader offset is due to one edge case for getting in-sync replica (ISR). 
Say we have a 5-member raft cluster, and use (_majority index_ - _match index_) as each peer's lag for detecting slow followers. If two followers are in-sync for some time, and the other two are slow. Once the two in-sync followers crash, the _majority index_ will be much smaller. In that case, the two slower followers will start serve read requests before they catch up with the leader.

2022-03-25 04:55 UTC, huyumars submitted a review, later dismissed

2022-03-25 11:05 UTC, huyumars approved these changes

2022-03-25 11:05 UTC, merged